### PR TITLE
Make Docker image smaller + some fixes

### PR DESCRIPTION
**Pull request by morsik**
- cleanup whitespaces
- use absolute paths to supervisor config and certbot-auto download path
- do apt-get install at once (image size: 480MB -> 453MB)
- cleanup apt after doing work (image size: 453MB -> 415MB)
- remove wget and use only curl to downloading certbot-auto (image size: 415MB -> 414MB)
- remove gcc and *-dev packages after they are used by certbot bootstrap (image size: size 414MB -> 267MB)

See progress:
```
openhades/docker-flow-letsencrypt   <none>              e697391bbe8f        21 minutes ago      267.6 MB
openhades/docker-flow-letsencrypt   <none>              86bc957d6837        About an hour ago   414.7 MB
openhades/docker-flow-letsencrypt   <none>              cde7e51c1c2b        About an hour ago   415.3 MB
openhades/docker-flow-letsencrypt   <none>              b64d567b3a7a        About an hour ago   453.5 MB
hamburml/docker-flow-letsencrypt    <none>              8b06c0ea012f        4 weeks ago         480 MB
```

I'm not sure if this is correct way to do this since there is `certbot-auto`, but… it's started with `--no-self-upgrade` anyway, so…

**Merge this AFTER #21 or you'll have broken ENV!**

### CODE REVIEW

**Comment by hamburml** [comment]
This looks totally great! The size reduction is incredible with 'just' some apt-get commands. Lovely! I feel so guilty for neglecting this project, had some family issues, health checks and to set up a company is time consuming ;). I added `--no-self-upgrade` because after a major certbot-auto update some arguments changed and I wanted to make sure that it's not auto updated. Thank you for your hard work!

**Comment by hamburml** [comment]
What does the `DEBIAN_FRONTEND` env do which was added to the dockerfile?

**Comment by morsik** [comment]
@hamburml: well… as I looked it does nothing in this case actually. Normally it tells apt not to asking questions like "Enter MySQL root password" but instead install with defaults. It's just for automatic Docker installation, but as I saw, it doesn't do that anyway because `apt-utils` is not installed inside container anyway.

Added for sake of corectness.

**Comment by hamburml** [comment]
Docker Cloud currently takes some more time to build the image. I will test the image later, thanks again! If you want you can check the latest-tag in some minutes https://hub.docker.com/r/hamburml/docker-flow-letsencrypt/tags/ and try it out.

**Pull request merged**
